<?php
require_once __DIR__ . '/config/auth.php';
?>
<?php 
$pageTitle = 'Privacy Policy';
include_once __DIR__ . '/includes/landing_header.php'; 
?>

    <div class="legal-header">
        <div class="container">
            <h1>Privacy Policy</h1>
            <p class="opacity-75">Last Updated: <?= date('F j, Y') ?></p>
        </div>
    </div>

    <div class="container mb-5">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="legal-content">
                    
                    <div class="legal-section">
                        <h2>1. Introduction</h2>
                        <p>Welcome to Lead CRM. We respect your privacy and are committed to protecting your personal data. This Privacy Policy outlines how we collect, use, process, and disclose your information, particularly regarding our integration with Meta Platforms (Facebook Lead Ads).</p>
                    </div>

                    <div class="legal-section">
                        <h2>2. Information We Collect</h2>
                        <p>When you use our SaaS platform, we collect the following types of data:</p>
                        <ul>
                            <li><strong>Account Data:</strong> Name, email address, password, phone number, and organization details when registering for an account.</li>
                            <li><strong>Meta Integration Data:</strong> If you connect your Facebook Page to our platform, we receive a Page Access Token and retrieve metadata about your Lead Generation Forms. This authorizes our system to listen to Webhook payloads on your behalf.</li>
                            <li><strong>Customer Leads Data:</strong> When prospective customers submit a Lead Ad form on your Facebook or Instagram pages, Meta sends that data securely to our webhooks. We store the names, phone numbers, emails, and custom questions submitted by those prospects directly into your private CRM database.</li>
                        </ul>
                    </div>

                    <div class="legal-section">
                        <h2>3. How We Use the Data</h2>
                        <p>The data we collect is used exclusively for providing and improving the CRM service. Specifically:</p>
                        <ul>
                            <li>To synchronize leads from Facebook to your CRM dashboard in real-time.</li>
                            <li>To allow your Sales Agents to view, contact, and manage leads autonomously.</li>
                            <li>To provide statistical reporting on your Organization's performance.</li>
                            <li>We <strong>DO NOT</strong> sell, rent, or trade your organization's leads to any third parties whatsoever. Your leads belong solely to you.</li>
                        </ul>
                    </div>

                    <div class="legal-section">
                        <h2>4. Third-Party Integrations (Meta Platforms)</h2>
                        <p>Lead CRM utilizes the Facebook Graph API to manage Lead Gen Webhooks. By using the "Connect Facebook" feature, you authorize us to receive data according to Meta's Platform Terms. We strictly adhere to the data usage limitations imposed by the Meta Developer Policies.</p>
                    </div>

                    <div class="legal-section">
                        <h2>5. Data Security & Multi-Tenancy</h2>
                        <p>Our platform is built on an isolated multi-tenant architecture. Every lead imported into the system is strictly bound to your `organization_id`. Sales Agents and Team Leads cannot view leads generated by a different organization. We use industry-standard encryption protocols (HTTPS/TLS) to secure data in transit.</p>
                    </div>

                    <div class="legal-section">
                        <h2>6. Your Data Rights & Deletion</h2>
                        <p>You have full ownership of your data. You may export your leads at any time. If you wish to permanently delete your organization and all associated Meta leads from our databases, the Organization Owner can initiate a full deletion request from the Settings panel.</p>
                        <p>For more specific instructions regarding the removal of Facebook app authorizations, please see our <a href="data-deletion.php">Data Deletion Instructions</a>.</p>
                    </div>

                    <div class="legal-section">
                        <h2>7. Contact Us</h2>
                        <p>If you have any questions about this Privacy Policy, please contact our support team at <strong>privacy@leadcrm.com</strong>.</p>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <?php include_once __DIR__ . '/includes/landing_footer.php'; ?>
